name: Compile AHK to EXE

on:
  push:
    paths:
      - '**.ahk'
      - .github/workflows/ahk-compile.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up AutoHotkey (download portable version)
      run: |
        Invoke-WebRequest -Uri https://www.autohotkey.com/download/ahk.zip -OutFile ahk.zip
        Expand-Archive ahk.zip -DestinationPath AHK

    - name: Compile AHK script
      run: |
        $compiler = "AHK\Compiler\Ahk2Exe.exe"
        $input = "SimpleTUOLiveSim.ahk"
        $output = "SimpleTUOLiveSim.exe"
        & $compiler /in $input /out $output
      shell: powershell

    - name: Compile AHK script
      run: |
        $compiler = "AHK\Compiler\Ahk2Exe.exe"
        $input = "SimpleTUOptimizeStarter.ahk"
        $output = "SimpleTUOptimizeStarter.exe"
        & $compiler /in $input /out $output
      shell: powershell

    - name: Upload compiled EXE
      uses: actions/upload-artifact@v4
      with:
        name: compiled-exe
        path: SimpleTUOptimizeStarter.exe

    - name: Upload compiled EXE
      uses: actions/upload-artifact@v4
      with:
        name: compiled-live-exe
        path: SimpleTUOLiveSim.exe
