name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: ubuntu
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04  # Use older Ubuntu version
    env:
      DEBIAN_FRONTEND: noninteractive  # âœ… Set globally for all steps

    steps:
      - name: Install Tools
        run: |
          apt-get update
          apt-get install -y git sudo gnupg software-properties-common python3-pip
          ln -fs /usr/share/zoneinfo/Etc/UTC /etc/localtime
          echo "Etc/UTC" > /etc/timezone
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      # early release creation to adjust release notes acc. to changelog after pushing git tag
      - name: Create Release
        if: contains(github.ref, 'tags/v')
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      # Build it
      - run: "./build/windows/requirements.sh"
      - run: "./build/windows/build.sh"
      - run: ./update_xml.sh
      - run: . build/windows/package.sh
      - name: Upload tuo
        uses: actions/upload-artifact@v4
        with:
          name: tuo
          path: |
            *.exe
            *.zip
      - name: upload windows artifact
        if: contains(github.ref, 'tags/v')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: tuo.zip
          asset_name: tuo.zip
          asset_content_type: application/zip
